### ISSUE TITLE
Install xgrid

### ISSUE THREAD

**Issue by jolorenzo** [genouest/xgrid#1]
Hi, I have a problem during installation of xgrid. I installed all the dependencies required but the following message is displayed when using the dpkg.

```
$ dpkg -i xgrid_1.3.7_wheezy.deb 
(Reading database ... 154119 files and directories currently installed.)
Preparing to unpack xgrid_1.3.7_wheezy.deb ...
Stopping xgrid web management: No rackup found running; none killed.
invoke-rc.d: initscript xgrid, action "stop" failed.
dpkg: warning: subprocess old pre-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
Stopping xgrid web management: No rackup found running; none killed.
invoke-rc.d: initscript xgrid, action "stop" failed.
dpkg: error processing archive xgrid_1.3.7_wheezy.deb (--install):
 subprocess new pre-removal script returned error exit status 1
Starting xgrid web management: Xgrid has not been initialized yet
Errors were encountered while processing:
 xgrid_1.3.7_wheezy.deb
```

So I tried to start rackup but an error appears:

```
$ rackup 
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /root/config/environment (LoadError)
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /root/config.ru:3:in `block in <main>'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:51:in `instance_eval'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:51:in `initialize'
    from /root/config.ru:1:in `new'
    from /root/config.ru:1:in `<main>'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:40:in `eval'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:40:in `parse_file'
    from /usr/lib/ruby/vendor_ruby/rack/server.rb:200:in `app'
    from /usr/lib/ruby/vendor_ruby/rack/server.rb:301:in `wrapped_app'
    from /usr/lib/ruby/vendor_ruby/rack/server.rb:252:in `start'
    from /usr/lib/ruby/vendor_ruby/rack/server.rb:137:in `start'
    from /usr/bin/rackup:4:in `<main>'
```

**Comment by osallou** [comment]
at installation rackup is not present, this is ok, service should not be started.
rackup is installed when the VM is started in an init script from ruby gem.

We usually install xgrid via bootstrap-vz (in a chroot ) to create the VM, where services at not started at package install, and it works fine. Then, when VM is started, it executes an init script that install missing deps.
Indeed, xgrid is not supposed to be started at install, only at VM startup.

If you install it manually directly in the VM, you have 2 solutions:
- RUNLEVEL=1 dpkg -i xx.deb

or
- dpkg --no-trigger -i xx.deb

or 
- install yourself the dependencies
  
  gem install dm-core dm-sqlite-adapter dm-migrations amazon-ec2 rack rack-protection --no-ri --no-rdoc
